### ISSUE TITLE
should config specify registry for images?

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#22]
``` yaml
imageConfig:
  format: openshift3_beta/ose-${component}:${version}
  latest: false
```

Do we want registry.access....openshift3_beta... ?
