### ISSUE TITLE
[v3-beta4] installer fails

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#25]
```
TASK: [openshift_master | Create master config] ******************************* 
failed: [ose3-master.example.com] => {"changed": true, "cmd": ["/usr/bin/openshift", "start", "master", "--write-config", "--config=/etc/openshift/master.yaml", "--portal-net=172.30.17.0/24", "--master=https://ose3-master.example.com:8443", "--public-master=https://ose3-master.example.com:8443", "--listen=https://0.0.0.0:8443", "--images=openshift3_beta/ose-${component}:${version}"], "delta": "0:00:00.735496", "end": "2015-05-05 19:45:47.363989", "rc": 1, "start": "2015-05-05 19:45:46.628493", "warnings": []}
stderr: Error: flag needs an argument: --write-config
Run 'openshift help' for usage.

FATAL: all hosts have already failed -- aborting
```

Not sure if I have the latest vars and such. Going to double check.

**Comment by thoraxe** [comment]
The syntax of `--config` and `--write-config` has changed.

It looks like `--write-config` expects a directory as an argument (eg: `/etc/openshift/master`) and `--config` actually doesn't do the same thing anymore.

Now it appears that `--config` expects a file as **input** that will provide all of the configuration options.

`--write-config` appears to only want to write out `master-config.yaml` and I don't see anywhere to change it. Specifying a full filename like `--write-config=/etc/openshift/master/default.yaml` creates a **folder** called `default.yaml`, which is not what we want.

I'm messing around with Ansible now but I ended up getting past this issue and am now having certificate issues.

**Comment by thoraxe** [comment]
So I tweaked some vars:

```
openshift_master_config_dir: /etc/openshift/master
openshift_master_config: /etc/openshift/master/master-config.yaml
openshift_master_ca_dir: "{{ openshift_cert_dir }}/ca"
openshift_master_ca_cert: "{{ openshift_master_ca_dir }}/cert.crt"
openshift_master_ca_key: "{{ openshift_master_ca_dir }}/key.key"
```

And then modified the "Create master config" section:

```
- name: Create master config
  command: >
    /usr/bin/openshift start master --write-config={{ openshift_master_config_dir }}
    --portal-net={{ openshift.master.portal_net }}
    --master={{ openshift.master.api_url }}
    --public-master={{ openshift.master.public_api_url }}
    --listen={{ 'https' if openshift.master.api_use_ssl else 'http' }}://0.0.0.0:{{ openshift.master.api_port }}
    {{ ('--images=' ~ openshift_registry_url) if (openshift_registry_url | default('', true) != '') else '' }}
    {{ ('--nodes=' ~ openshift_node_ips | join(',')) if (openshift_node_ips | default('', true) != '') else '' }}
  args:
    chdir: "{{ openshift_cert_parent_dir }}"
    creates: "{{ openshift_master_config }}"
```

This results in the following `/etc/openshift/master/master-config.yaml`:

``` yaml
apiVersion: v1
assetConfig:
  logoutURL: ""
  masterPublicURL: https://192.168.133.2:8443
  publicURL: https://192.168.133.2:8443/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
corsAllowedOrigins:
- 127.0.0.1
- 192.168.133.2:8443
- localhost
dnsConfig:
  bindAddress: 0.0.0.0:53
etcdClientInfo:
  ca: ca.crt
  certFile: master.etcd-client.crt
  keyFile: master.etcd-client.key
  urls:
  - https://192.168.133.2:4001
etcdConfig:
  address: 192.168.133.2:4001
  peerAddress: 192.168.133.2:7001
  peerServingInfo:
    bindAddress: 0.0.0.0:7001
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
  servingInfo:
    bindAddress: 0.0.0.0:4001
    certFile: etcd.server.crt
    clientCA: ca.crt
    keyFile: etcd.server.key
  storageDirectory: /root/openshift-ansible/openshift.local.etcd
etcdStorageConfig:
  kubernetesStorageVersion: v1beta3
  openShiftStorageVersion: v1beta1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  masterIP: 192.168.133.2
  schedulerConfigFile: ""
  servicesSubnet: 172.30.0.0/16
  staticNodeNames: []
masterClients:
  deployerKubeConfig: openshift-deployer.kubeconfig
  externalKubernetesKubeConfig: ""
  openshiftLoopbackKubeConfig: openshift-client.kubeconfig
masterPublicURL: https://192.168.133.2:8443
oauthConfig:
  assetPublicURL: https://192.168.133.2:8443/console/
  grantConfig:
    method: auto
  identityProviders:
  - challenge: true
    login: true
    name: anypassword
    provider:
      apiVersion: v1
      kind: AllowAllPasswordIdentityProvider
  masterPublicURL: https://192.168.133.2:8443
  masterURL: https://192.168.133.2:8443
  sessionConfig:
    sessionMaxAgeSeconds: 300
    sessionName: ssn
    sessionSecretsFile: ""
  tokenConfig:
    accessTokenMaxAgeSeconds: 86400
    authorizeTokenMaxAgeSeconds: 300
policyConfig:
  bootstrapPolicyFile: policy.json
  masterAuthorizationNamespace: master
  openshiftSharedResourcesNamespace: openshift
projectRequestConfig:
  projectRequestMessage: ""
  projectRequestTemplate: openshift/project-request
servingInfo:
  bindAddress: 0.0.0.0:8443
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
```

So it appears that a bunch of stuff has moved around / been busted in the latest upstream 0.5.0.0 puddle.
